#!/bin/sh -e

regex='^!?ipfs-gw( .*)?$'

if [ -n "$CONFIG" ]
then
    echo $regex
    exit 0
fi

SELF_PATH=$(dirname $0)
RES_FILE="$SELF_PATH/../../csobot/ipfs-gateway-result.log"
[[ -f $RES_FILE ]] || echo "Oops, the list is not found."

echo "==== Today's IPFS gateway: ===="
cat $RES_FILE

exit
