#!/bin/bash

regex='^mail2matrix$'

if [ -n "$CONFIG" ]
then
    echo $regex
    exit 0
fi

HOME=/home/user
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
MAILBOX=$HOME/Maildir

#while true; do
    NEW_MAIL=$(find ${MAILBOX}/new -type f)
    if [[ -z $NEW_MAIL ]]; then
        echo "No new mail found. Cheers."
        #continue
    else
        for NM in $(echo "$NEW_MAIL"); do
            SUB=$(grep "Subject:" $NM)
            FROM=$(grep "From:" $NM)
            DATE=$(grep "Date:" $NM)
            echo "  ==== $DATE ===="
            echo $FROM
            echo $SUB
            mv $NM ${MAILBOX}/cur/
        done
    fi
    #sleep 60
# done

exit

